messages:
  prefix: "&dPractice ->" #Prefix for all messages, leave this blank if you don't want a preifx.
  no-permission: "&cYou don't have the required permission to execute this command!"
  no-args: "&cPlease provide an argument!"
  reload: "&aYou have successfully reloaded the training plugin"

  training-zombie:
    spawn:
      success: "&aTraining zombie has been spawned!"
    despawn:
      success: "&aTraining zombie has been despawned!"
      fail: "&cTraining zombie is not spawned!"

training-zombie:
  display-name: '&aTraining Zombie &8(%player%)' #You're able to use the %player% placeholder here to get the name off the user.